// Auto-generated by scripts/migrate-scenarios.mts. Do not edit by hand.
import type { EditorState } from '../../../editor/types';

import s0 from './attack/4v4-attack-losange';
import s1 from './attack/4v4-attack-penetrant';
import s2 from './attack/4v4-attack-square';
import s3 from './defense/4v4-defense-block-1';
import s4 from './defense/4v4-defense-vs-z2';
import s5 from './defense/4v4-defense-vs-z3';
import s6 from './reception/4v4-reception-losange';
import s7 from './reception/4v4-reception-u';
import s8 from './reception/5-1-reception-3-receivers';
import s9 from './attack/5v5-attack-pentagon';
import s10 from './defense/5v5-defense-vs-z2';
import s11 from './defense/5v5-defense-vs-z3';
import s12 from './defense/5v5-defense-vs-z4';
import s13 from './reception/5v5-reception-4-receivers';
import s14 from './reception/5v5-reception-pentagon';
import s15 from './attack/6v6-attack-4-2';
import s16 from './attack/6v6-attack-5-1-p1';
import s17 from './attack/6v6-attack-5-1-p2';
import s18 from './attack/6v6-attack-5-1-p3';
import s19 from './attack/6v6-attack-5-1-p4';
import s20 from './attack/6v6-attack-5-1-p5';
import s21 from './attack/6v6-attack-5-1-p6';
import s22 from './attack/6v6-attack-6-2';
import s23 from './defense/6v6-attack-coverage';
import s24 from './defense/6v6-defense-6-front';
import s25 from './defense/6v6-defense-perimeter';
import s26 from './defense/6v6-defense-read';
import s27 from './defense/6v6-defense-rotation';
import s28 from './defense/6v6-defense-vs-pipe';
import s29 from './defense/6v6-defense-vs-z2';
import s30 from './defense/6v6-defense-vs-z3';
import s31 from './defense/6v6-defense-vs-z4';
import s32 from './reception/6v6-reception-2-receivers';
import s33 from './reception/6v6-reception-4-2';
import s34 from './reception/6v6-reception-rotation-p4';
import s35 from './reception/6v6-reception-semi-circle';
import s36 from './reception/6v6-reception-w';

export const EDITOR_STATES: ReadonlyArray<EditorState> = [
  s0,
  s1,
  s2,
  s3,
  s4,
  s5,
  s6,
  s7,
  s8,
  s9,
  s10,
  s11,
  s12,
  s13,
  s14,
  s15,
  s16,
  s17,
  s18,
  s19,
  s20,
  s21,
  s22,
  s23,
  s24,
  s25,
  s26,
  s27,
  s28,
  s29,
  s30,
  s31,
  s32,
  s33,
  s34,
  s35,
  s36,
];
