import type { CSSProperties } from 'react';

// Tokens shared across quiz components. Mirrors src/guides/styles.ts for
// visual consistency: same paper card, same ink border, same flat shadow.
export const Q = {
  card: {
    background: 'var(--paper)',
    border: '2.5px solid var(--ink)',
    padding: '20px 22px',
    boxShadow: 'var(--shadow-sm)',
  } as CSSProperties,
  // Pressable option button. Picks up active/correct/incorrect via overrides.
  option: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    background: 'var(--cream)',
    border: '2.5px solid var(--ink)',
    padding: '12px 14px',
    fontFamily: '"DM Sans", sans-serif',
    fontSize: 14,
    color: 'var(--ink)',
    textAlign: 'left' as const,
    cursor: 'pointer',
    boxShadow: '2px 2px 0 var(--ink)',
    transition: 'transform 0.08s, box-shadow 0.08s, background 0.08s',
  } as CSSProperties,
  optionHover: {
    transform: 'translate(-2px, -2px)',
    boxShadow: '4px 4px 0 var(--ink)',
  } as CSSProperties,
  optionCorrect: {
    background: 'var(--teal)',
    color: 'var(--cream)',
    cursor: 'default',
    transform: 'none',
    boxShadow: '2px 2px 0 var(--ink)',
  } as CSSProperties,
  optionIncorrect: {
    background: 'var(--yellow)',
    color: 'var(--ink)',
    cursor: 'default',
    transform: 'none',
    boxShadow: '2px 2px 0 var(--ink)',
  } as CSSProperties,
  optionDisabled: {
    cursor: 'default',
    opacity: 0.55,
    transform: 'none',
    boxShadow: '2px 2px 0 var(--ink)',
  } as CSSProperties,
  optionLetter: {
    width: 24,
    height: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--ink)',
    color: 'var(--cream)',
    fontFamily: '"Bungee", sans-serif',
    fontSize: 11,
    flexShrink: 0,
  } as CSSProperties,
  feedbackCorrect: {
    background: 'var(--teal)',
    color: 'var(--cream)',
    border: '2.5px solid var(--ink)',
    padding: '14px 18px',
    boxShadow: 'var(--shadow-sm)',
  } as CSSProperties,
  feedbackIncorrect: {
    background: 'var(--yellow)',
    color: 'var(--ink)',
    border: '2.5px solid var(--ink)',
    padding: '14px 18px',
    boxShadow: 'var(--shadow-sm)',
  } as CSSProperties,
  cta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    background: 'var(--orange)',
    color: 'var(--cream)',
    border: '2.5px solid var(--ink)',
    padding: '12px 22px',
    fontFamily: '"Bungee", sans-serif',
    fontSize: 13,
    letterSpacing: '0.08em',
    cursor: 'pointer',
    boxShadow: 'var(--shadow-sm)',
    transition: 'transform 0.08s, box-shadow 0.08s',
  } as CSSProperties,
  ctaSecondary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    background: 'var(--cream)',
    color: 'var(--ink)',
    border: '2.5px solid var(--ink)',
    padding: '12px 22px',
    fontFamily: '"Bungee", sans-serif',
    fontSize: 13,
    letterSpacing: '0.08em',
    cursor: 'pointer',
    boxShadow: 'var(--shadow-sm)',
    transition: 'transform 0.08s, box-shadow 0.08s',
  } as CSSProperties,
  // Progress bar — same stripe vocabulary as the Layout banner.
  progressTrack: {
    height: 8,
    background: 'var(--cream)',
    border: '2.5px solid var(--ink)',
    overflow: 'hidden',
  } as CSSProperties,
  progressFill: {
    height: '100%',
    background: 'var(--orange)',
    transition: 'width 0.25s ease-out',
  } as CSSProperties,
};
